# base image
# FROM node:24.11.0 AS build

FROM node:20-alpine AS build

# set work directory
WORKDIR /app

#install dependancies
COPY package.json package-lock.json ./

RUN npm install

COPY . .
RUN npm run build

#production stage

FROM nginx:1.25-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

CMD [ "nginx", "-g", "daemon off;"]